# Generated by Django 4.1.3 on 2022-11-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computadore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dono_do_pc', models.CharField(max_length=100)),
                ('processador', models.CharField(max_length=100)),
                ('placa_mae', models.CharField(max_length=100)),
                ('placa_de_video', models.CharField(max_length=100)),
                ('memoria_ram', models.CharField(max_length=100)),
                ('possui_ssd_ou_hd', models.BooleanField(blank=True, null=True)),
                ('quantos_ssd_ou_hd', models.IntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
